### ISSUE TITLE
Sprint 2 - 2024

### ISSUE THREAD

**Issue by cloverich** [cloverich/chronicles#123]
After #116 , this represents the next phase of work I plan to do. Project should be ramped up again, and stage set to work on _real_ features. 

Themes:
* Core markdown / block type support
* Advanced note features / UX

## Core blocks
Support all core block types, and ensure the toolbar can be used to toggle / insert each supported type. If it is not crazy complicated, try to support entering markdown and live turning it into the correct slate node type.

- [x] #103 
- [x] #166 
- [x] #168
- [x] #85
- [x] #184
- [x] #80 (Stretch)

## Improved editor and nav UX
This represents the key features I use from other note taking applications, that are missing in Chronicles. This is beyond the base usability and into the stuff that makes the application truly useful. Its also the stuff I'd need to knock out before I'd be comfortable dropping all my other notes app usages.

- [ ] #124 **defer**: Do with design sprint, need context menu (several features need this)
- [x] #170 (also, create then back)
- [x] #189 
- [ ] #125 **defer**: priority
- [x] #126
- [x] #202
- [ ] #127 **defer**: priority - pair w/ markdown / import export / database-like features
- [ ] #104 **defer**: complexity; tackle when I have more time

## Misc
If it drives me nuts while developing this Sprint I'm adding it here and doing it

- [x] #173
- [ ] #174 **defer** tackle alongside esm support, after design (refactor) sprint
- [ ] #181 **defer** priority
- [ ] #183 **defer** complexity
- [x] #71

**Comment by cloverich** [comment]
[It is ](https://github.com/cloverich/chronicles/releases/tag/v0.5.0) marks the close of this sprint. Did not quite get to everything I wanted, but hit a more important milestone: I'm now using the application for my daily note taking. No breaks between this sprint and the next, onward it is.
