### ISSUE TITLE
Roadmap: Base Usability

### ISSUE THREAD

**Issue by cloverich** [cloverich/chronicles#69]
This roadmap document covers all the issues I plan on addressing imminently. The goal is to achieve a base level of usability in the application. You should be able to understand its core value proposition and install and run it. Once running, you should be able to view and write documents in a basic sense. 

I write this document after completing a moderate departure from my original idea and after I have just begun dogfooding: I am using the app as my daily notes driver, despite its flaws and very raw state, to help keep me focused on the most important issues. This will not include polish or any features that would make the app generally appealing, only those that would keep me from using it as a daily note taker. 

## Important UX features and their dependencies
These features cover basic usability and dependencies related to it. At a base level that means being able to create, update, and delete documents. 

- [x] Setup auto saving of documents #67 
- [x] #70

There are numerous issues with the current editor. After reviewing the Slate examples I had hoped I could implement a full set of basic wysiwyg features but many turned out to be more complex than I anticipated:

- [x] #48 
- [x] #36 
- [x] Reasonable styling of code blocks, quotes, etc

...and a few more. Rather than sink all my time into this, I'd like to try a higher level abstraction and, failing that, another editor with more out of the box functionality:

- [x] Migrate to plate (and issues related to it) #68 

## Search features
Search and a good UX around it are crucial. I want to stick to my [highly constrained](https://pinecoder.dev/blog/2020-10-09/search-tags-interface) UI but ensure the base set of features around it are solid -- particularly navigating to and from search and handling pagination properly.

- [x]  #35 
- [x] #39 
- [x] #34 

## Issues related to using the packaged app
The app should be installable and setup its database correctly. It should not have any glaring security issues that would make it unsafe nor any dead ends, particularly thinking of empty states.

- [ ] Security (#53 )
- [x] Database setup (#63 )
- [x] #38 
- [ ] Document value proposition
